### ISSUE TITLE
Cannot serve request to /libs/wcm/core/content/pageinfo.json in com.day.cq.wcm.core.impl.servlets.PageInfoServlet

### ISSUE THREAD

**Issue by sreenu539** [adobe/aem-sample-we-retail-journal#63] opened 2019-12-04 18:55 UTC
Cannot serve request to /libs/wcm/core/content/pageinfo.json in com.day.cq.wcm.core.impl.servlets.PageInfoServlet

I am getting 404 for pageInfo.json request and page is in preview mode, not able to click any links or buttons and change to different mode as "FullScreenMask" css from aem code applied.

<img width="1431" alt="Screen Shot 2019-12-04 at 11 10 58 AM" src="https://user-images.githubusercontent.com/47572504/70171916-ea475f80-168c-11ea-984a-a3e13383e948.png">
<img width="459" alt="Screen Shot 2019-12-04 at 10 56 00 AM" src="https://user-images.githubusercontent.com/47572504/70171932-efa4aa00-168c-11ea-8fe1-60d2b286fbb9.png">

Env: AEM 6.3.3 , AEM 6.5.1 - this seems to be issue with one page at this time.

**Comment by habansal** [comment] 2019-12-05 07:34
@sreenu539 Can you please provide more details about how to reproduce the issue ?
> this seems to be issue with one page at this time.

Which page ?

**Comment by pfauchere** [comment] 2020-08-12 13:30
No answer, closing the issue

**Closed as completed by pfauchere** 2020-08-12 13:30 UTC

**Comment by vineetkaushikmca** [comment] 2020-10-20 13:57
We are facing same issue after upgrade from 6.4.5 to 6.5.6
https://localhost:4502/libs/wcm/core/content/pageinfo.json does not pull any data rather show blank screen.
please let me know what can be the cause?
