### ISSUE TITLE
Angular tests make Cloud Manager pipeline fail

### ISSUE THREAD

**Issue by keepthebyte** [adobe/aem-sample-we-retail-journal#43] opened 2019-03-21 04:54 UTC
If I remove the line `"test": "ng test --watch=false",` from package.json in angular-app then it works. Wondering if there is another way to do this that would work.

Cloud Manager pipeline stops with

```
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! angular-app@1.1.1 test: `ng test --watch=false`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the angular-app@1.1.1 test script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by justinedelson** [comment] 2019-03-21 14:44
@keepthebyte if you look right above that in the log, you should see this which tells you what the problem is:

```
[INFO] 21 03 2019 12:13:01.002:INFO [karma]: Karma v3.0.0 server started at http://0.0.0.0:9876/
[INFO] 21 03 2019 12:13:01.013:INFO [launcher]: Launching browser Chrome with unlimited concurrency
[INFO] 21 03 2019 12:13:01.026:INFO [launcher]: Starting browser Chrome
[INFO] 21 03 2019 12:13:01.028:ERROR [launcher]: No binary for Chrome browser on your platform.
[INFO]   Please, set "CHROME_BIN" env variable.
```

It's interesting that this isn't a problem for the react tests.

I tried installing Chromium (see https://github.com/justinedelson/aem-sample-we-retail-journal/commit/156b1def460f6ba74ea241c322e345d6e364202d), but I get the same error.

Does the build actually require Chrome proper?

**Comment by keepthebyte** [comment] 2019-03-21 14:48
when i build it locally - then it does open Chrome Browser window for real. Hence I think this needs to be adjusted so it can run headless.

**Comment by justinedelson** [comment] 2019-03-21 21:14
can you reassign this to someone who knows how to do that?

**Comment by justinedelson** [comment] 2019-03-22 11:21
It looks like if Chrome (not Chromium) is installed, it works. See https://github.com/adobe/aem-sample-we-retail-journal/compare/master...justinedelson:cmcompat?expand=1

**Comment by gknobloch** [comment] 2019-03-23 10:54
@keepthebyte @justinedelson FYI, our CircleCI uses a Docker image that has Chrome installed
https://github.com/adobe/aem-sample-we-retail-journal/blob/master/.circleci/config.yml#L19

**Comment by norbiorb** [comment] 2019-03-25 11:01
Compared to react-app one difference is indeed that for react-app the browser is configured using : `--browsers=ChromeHeadless` . So if react-app tests are passing then one could change angular test run also to use headless chrome to see if that works (`"test": "ng test --watch=false --browsers=ChromeHeadless"` ). Otherwise there is CI setup available for angular which uses https://github.com/vvo/selenium-standalone docker images and tests can be run using `npm run test:ci`. So one needs to know what is available on Cloud Manager pipeline  setup.

**Comment by pfauchere** [comment] 2019-04-01 19:04
The Cloud Manager pipeline doesn't support the installation of any binary - including ChromeHeadless. We may have to wait for having Evergreen to work with the Cloud Manager pipeline. And then we could split the operation into two steps to have the unit tests executed by Evergreen but not by the Cloud Manager pipeline.

More info:

The unit tests are not executed in the React project when it is being built by Maven. In the Angular project though, there is a profile called `local` [0] that is activated by default and responsible for executing the unit tests. The two Maven descriptors need to be aligned. 

As a temporary solution, the following command should deactivate the Angular profile called `local`

`mvn clean install -Plocal.activation.activeByDefault=false`

[0] https://github.com/adobe/aem-sample-we-retail-journal/blob/master/angular-app/pom.xml#L127-L154

**Comment by justinedelson** [comment] 2019-04-01 19:49
> The Cloud Manager pipeline doesn't support the installation of any binary - including ChromeHeadless. 

This is not true. The build process runs as root so you can do whatever you want -- install Chromium, Chrome, Firefox, whatever. The commits I linked to show how this can be done. Chromium is a lot easier since that's available in a default apt repository. But Chrome is doable as well. See the commits I linked to.

> As a temporary solution, the following command should deactivate the Angular profile called local

You could do this by adding a test to only activate this profile when the build is run outside of Cloud Manager. See https://docs.adobe.com/content/help/en/experience-manager-cloud-manager/using/getting-started/create-an-application-project.html#activating-maven-profiles-in-cloud-manager

**Comment by pfauchere** [comment] 2019-04-03 04:52
Hi @justinedelson, thx for the feedback. How do you interpret the following log extract? 

Edit: Hmm I missed the `Chromium` part of the conversation and got confused with `ChromeHeadless`! I'll switch to and test right away. Would `ChromiumHeadless` also work?

```
[INFO] 01 04 2019 18:35:14.563:INFO [karma]: Karma v3.0.0 server started at http://0.0.0.0:9876/
[INFO] 01 04 2019 18:35:14.566:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
[INFO] 01 04 2019 18:35:14.570:INFO [launcher]: Starting browser ChromeHeadless
[INFO] 01 04 2019 18:35:14.571:ERROR [launcher]: No binary for ChromeHeadless browser on your platform.
[INFO]   Please, set "CHROME_BIN" env variable.
```

**Comment by pfauchere** [comment] 2019-04-11 09:32
Resolved via

https://github.com/adobe/aem-sample-we-retail-journal/commit/b87992b7023bfb824b964b7212db17d1e98a144f

**Closed as completed by pfauchere** 2019-04-11 09:32 UTC
